### ISSUE TITLE
v1.1 update roadmap

### ISSUE THREAD

**Issue by dromzeh** [dromzeh/qbit-rpc#1]
- [ ] Allow for more `customization` of the RPC (to be auto set through `CLI` or `config.json`)
- [ ] Focus on `specific stats` of a torrent.
- [ ] Fix auto-updating system w/ `git` using `checkForUpdates` function.
- [ ] Improvements towards the `CLI`.
- [ ] Update `README.md`.
